### ISSUE TITLE
Failure with dev version of haven

### ISSUE THREAD

**Issue by hadley** [rubenarslan/codebook#25]
```R
library(codebook)

packageVersion("haven")
packageVersion("codebook")

data("bfi")
bfi <- bfi[,c("BFIK_open", paste0("BFIK_open_", 1:4))]
codebook_component_scale(bfi[,1], "BFIK_open", bfi[,-1],
   reliabilities = list(BFIK_open = psych::alpha(bfi[,-1])))
#> Error: C stack usage  7969280 is too close to the limit
```

I'm not sure exactly what is causing this, but it's probably related to the changes to the [labelled class](https://github.com/tidyverse/haven/blob/master/NEWS.md#breaking-changes).

Could you please take a look? I'm planning on submitting haven 2.0 to CRAN on [November 7](https://github.com/tidyverse/haven/issues/399)

**Comment by rubenarslan** [comment]
This is fixed since shortly after your first revdep email, and doesn't occur anymore with codebook 0.7.0 (but it's not on CRAN because I understood you to say that I should wait with submitting until after haven is accepted, because I cannot fix codebook for haven 2.0.0 without breaking it with haven < 1.2).

**Comment by hadley** [comment]
Ok, great, thanks!

**Comment by hadley** [comment]
(Sorry for the noise, I managed to mess up the revdeps so wanted to double check with everyone affected)
